// src/renderer/App.vue
<template>
  <div id="app">
    <div v-if="process.platform === 'darwin'" style="-webkit-app-region: drag; height: 20px"></div>
    <router-view></router-view>
  </div>
</template>

<script>
  export default {
    name: 'youtube-dl-gui',
    computed: {
      process () {
        return process
      }
    }
  }
</script>

<style>
  /* CSS */
</style>

// src/App.tsx
import React from 'react'
import { HashRouter, Route } from 'react-router-dom'
import Landing from './views/Landing'

function App() {
  return (
    <>
      {global.process.platform === 'darwin' && (
        <>
          <div
            style={{
              width: '100vw',
              height: 35,
              /* @ts-ignore */
              WebkitAppRegion: 'drag',
              position: 'fixed',
            }}
          />
        </>
      )}
      <div
        style={{
          padding: 40,
        }}
      >
        <HashRouter>
          <Route exact path='/' component={Landing} />
        </HashRouter>
      </div>
    </>
  )
}

export default App
